"""
Debriefing content for the Qualtrics post-survey.

Includes study purpose explanation, condition disclosure (piped text),
correct analysis for each scenario (S1, S2, S3), research contact info,
and a thank-you message.
"""

DEBRIEFING_BLOCK_NAME = "B6: Debriefing"

DEBRIEFING_TEXT = (
    "<h2>Debriefing</h2>"
    "<p>Thank you for completing this study! Below is some information about "
    "what you just participated in.</p>"
    "<hr>"
    "<h3>Study Purpose</h3>"
    "<p>This study investigates how the <strong>order of instructional "
    "activities</strong> affects learning about causal inference in "
    "communication research. Specifically, we compare two instructional "
    "sequences:</p>"
    "<ul>"
    "<li><strong>Instruction → Problem-Solving (I→PS):</strong> Participants "
    "first read instructional material, then discuss research scenarios with "
    "an AI tutor.</li>"
    "<li><strong>Problem-Solving → Instruction (PS→I):</strong> Participants "
    "first discuss research scenarios with an AI tutor, then read "
    "instructional material.</li>"
    "</ul>"
    "<p>Both groups received <em>exactly the same content</em> — only the "
    "order differed.</p>"
    "<h3>Your Condition</h3>"
    "<p>You were randomly assigned to the "
    "<strong>${e://Field/condition}</strong> condition.</p>"
    "<hr>"
    "<h3>Correct Analyses for the Practice Scenarios</h3>"
    "<p>During the AI tutoring session, you analysed three research "
    "scenarios. Here are the key methodological issues in each:</p>"
    "<h4>Scenario 1: ConnectU and Depressive Symptoms</h4>"
    "<p>The study described was <strong>cross-sectional and "
    "observational</strong>. It found a correlation between social media use "
    "and depressive symptoms, but this does not establish causation. The "
    "researchers' conclusion that ConnectU 'leads to' depressive symptoms "
    "is not supported because:</p>"
    "<ul>"
    "<li>The causal direction could be reversed (people with depressive "
    "symptoms might use social media more).</li>"
    "<li>Third variables (e.g., loneliness, personality traits) could "
    "explain both increased social media use and depressive symptoms.</li>"
    "<li>Without an experimental design, correlation cannot demonstrate "
    "causation.</li>"
    "</ul>"
    "<h4>Scenario 2: Political Debate Viewing and Political Knowledge</h4>"
    "<p>The study concluded that watching political debates increases "
    "political knowledge, but it failed to account for <strong>third-variable "
    "confounding</strong>. The key confound is <strong>education level</strong> "
    "(or political interest): people with higher education are more likely "
    "to both watch political debates AND score higher on political knowledge "
    "tests. The observed association may be driven by this pre-existing "
    "difference rather than by debate viewing itself.</p>"
    "<h4>Scenario 3: Prosocial Media and Empathy (Two Schools)</h4>"
    "<p>This study used <strong>intact groups</strong> (School A vs. "
    "School B) rather than randomly assigning individual students to "
    "conditions. This creates a <strong>selection bias</strong>: the two "
    "schools may differ systematically (demographics, teaching quality, "
    "school culture) in ways that affect empathy scores. Any observed "
    "difference might be due to pre-existing school differences rather than "
    "the prosocial media programme.</p>"
    "<hr>"
    "<h3>What We Are Studying</h3>"
    "<p>We are investigating whether the 'productive failure' approach "
    "(struggling with problems before receiving instruction) leads to deeper "
    "learning compared to the traditional approach (instruction first). We "
    "are also examining how each approach affects cognitive load — the "
    "mental effort you experienced during the learning activities.</p>"
    "<h3>Contact Information</h3>"
    "<p>If you have any questions about this study or your participation, "
    "please contact:</p>"
    "<p>Jinyi Yang<br>"
    "Email: jinyi.yang@student.uva.nl<br>"
    "Department of Communication Science, University of Amsterdam</p>"
    "<p>If you have questions about your rights as a research participant, "
    "please contact the Ethics Review Board: "
    "<a href='mailto:ethics-fsw@uva.nl'>ethics-fsw@uva.nl</a></p>"
    "<hr>"
    "<p><strong>Thank you for your valuable contribution to this "
    "research!</strong></p>"
)

DEBRIEFING_ITEMS = [
    {
        "id": "debriefing_text",
        "type": "Display",
        "text": DEBRIEFING_TEXT,
    },
]
